In [142]:
import pandas as pd
df= pd.read_csv('file/chipotle.tsv',sep='\t')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [143]:
df.shape
df['order_id'].unique()
df.columns
# df.info()
#df.describe()

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [144]:
df['item_price'] = df['item_price'].str.replace('$', '').str.strip().astype(float)
df['order_id']= df['order_id'].astype(str)

In [145]:
# 1. 가장 많이 주문한(order_id) item_name 10개를 출력하시오.
df['item_name'].value_counts().head(10)

item_name
Chicken Bowl                    726
Chicken Burrito                 553
Chips and Guacamole             479
Steak Burrito                   368
Canned Soft Drink               301
Chips                           211
Steak Bowl                      211
Bottled Water                   162
Chicken Soft Tacos              115
Chips and Fresh Tomato Salsa    110
Name: count, dtype: int64

In [146]:
# 2. item_name 당 주문 총량(quantity) 순서로 출력하시오.
df.groupby('item_name')['quantity'].sum().sort_values(ascending=False)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [147]:
# 3. item_name 가장 많이 주문한 10개 출력하시오
df.groupby('item_name')['order_id'].count().sort_values(ascending=False).head(10)

#선생님 정답
# item_count.index[0]
#----------------------------
# item_count = df['item_name'].value_counts()[:10]
# item_count

item_name
Chicken Bowl           726
Chicken Burrito        553
Chips and Guacamole    479
Steak Burrito          368
Canned Soft Drink      301
Chips                  211
Steak Bowl             211
Bottled Water          162
Chicken Soft Tacos     115
Chicken Salad Bowl     110
Name: order_id, dtype: int64

In [148]:
# 주문상품 종류
df['item_name'].unique()[:10]

<StringArray>
[         'Chips and Fresh Tomato Salsa',
                                  'Izze',
                      'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
                          'Chicken Bowl',
                         'Side of Chips',
                         'Steak Burrito',
                      'Steak Soft Tacos',
                   'Chips and Guacamole',
                  'Chicken Crispy Tacos']
Length: 10, dtype: str

In [149]:
#람다식 타입변경
# df['item_price'] = df['item_price'].str.replace('$','').str.strip().astype(float)
# df['item_price'] = df['item_price'].apply(lambda x: float(x[1:]))
# df.describe()

In [150]:
#합계(아이템 같은 이름 수량 총 합계)
df.groupby('item_name')['quantity'].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [151]:
# 4. 주문당 평균 금액을 출력하시오.
df.groupby('order_id')['item_price'].sum().mean()

np.float64(18.811428571428568)

In [152]:
#5. 한 주문에 50달러 이상 사용한 주문 번호(id) 출력
chipo = df.groupby('order_id').sum()
results = chipo[chipo.item_price >= 50]

results.index.values
results[:10]

,quantity,item_name,choice_description,item_price
order_id,,,,
1006,8,Chicken Soft TacosVeggie BowlSteak BowlChicken...,"[Fresh Tomato Salsa, [Sour Cream, Lettuce]][Fr...",71.40
1051,7,Chicken BurritoSteak BowlChips and GuacamoleCh...,"[Tomatillo Red Chili Salsa, [Rice, Pinto Beans...",59.35
1360,6,Chicken Burrito6 Pack Soft DrinkSteak BurritoB...,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",52.18
1443,35,Chips and Fresh Tomato SalsaBottled Water6 Pac...,"[Coke][Fresh Tomato Salsa, [Fajita Vegetables,...",160.74
1449,11,Chicken BurritoSteak BurritoVeggie BowlChicken...,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",95.39
1454,10,6 Pack Soft DrinkChicken BurritoChicken Soft T...,"[Coke][Fresh Tomato Salsa][Fresh Tomato Salsa,...",85.24
1483,14,Chicken BowlSteak BowlChicken BurritoSteak Bow...,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",139.00
1559,16,Side of ChipsChicken Soft TacosVeggie Soft Tac...,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",82.44
1586,6,Chicken BurritoChicken BurritoChicken BurritoS...,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",51.20
1660,19,Chicken BurritoChipsCanned Soft DrinkChicken B...,"[Fresh Tomato Salsa, Rice][Coke][Fresh Tomato ...",70.25

In [153]:
#치킨볼을 2개 이상 구매한 주문서 출력하시오.
filt = (df['item_name']=='chicken Bowl')&(df['quantity']>=2)
df[filt]
#합계 sum 평균 mean

Empty DataFrame
Columns: [order_id, quantity, item_name, choice_description, item_price]
Index: []