In [77]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [8]:
#합계,평균,결과 컬럼을 추가
#결과 평균점수가 70점 이상은 합겨, 불합격으로 출력하시오

In [78]:
df['합계']= df['국어']+df['영어']+df['수학']
df['평균']= (df['합계']/3).round(2)
df['결과']='불합격'
df.loc[df['평균']>=70,'결과'] = '합격'
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계     평균   결과
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  275  91.67   합격
2번    강태원   구로고  184   40   35   50  55  25        Java  125  41.67  불합격
3번    강호림   구로고  168   80   75   70  80  75  Javascript  225  75.00   합격
4번    김수찬   구로고  187   40   60   70  75  80         NaN  170  56.67  불합격
5번    김재욱   구로고  188   15   20   10  35  10         NaN   45  15.00  불합격
6번    박동현  디지털고  202   80  100   95  85  80           C  275  91.67   합격
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  165  55.00  불합격
8번    승근열  디지털고  190  100   85   90  95  95          C#  275  91.67   합격

In [28]:
# 컬럼 순서변경
# df2= df[['이름','평균','결과']]
# df2

# df= df[['이름','평균','결과','학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계']]

            이름     평균   결과    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund  69.33  불합격   신림고   2  171  56  92  60       c  208
2       Kirbee  36.00  불합격   구로고   1  199  53  10  45       C  108
3    Appolonia  70.00   합격   구로고   3  193  77  52  81       C  210
4        Avery  45.67  불합격   구로고   2  187  59  35  43       C  137
5       Dallis  76.67   합격  디지털고   1  209  97  57  76       C  230
..         ...    ...  ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke  71.00   합격   신림고   3  187  91  63  59  Python  213
97        Nada  68.00  불합격   구로고   3  170  60  89  55  PYTHON  204
98       Fiona  92.00   합격   신림고   1  200  97  95  84       C  276
99        Leif  71.33   합격   구로고   2  192  96  84  34  PYTHON  214
100   Jonathan  75.67   합격  디지털고   2  195  84  63  80    JAVA  227

[100 rows x 11 columns]

In [ ]:
# cols = list(df.columns)

In [ ]:
# a_list = [1,2,3]
# b_list = [4,5,6]
# c= a_list+b_list  #리스트타입일 때만 더하기 가능
# c

[1, 2, 3, 4, 5, 6]

In [ ]:
# # [cols리스트 순서를 변경]

# #1. 리스트 타입으로 변경 후 순서를 변경
# cols = list(df.columns)

# # cols[-2:] #평균,결과 컬럼
# # type(cols[0]) #str -> list타입으로 변경하려면 []로 묶어야 함
# # type(cols[1:-2]) #list 이름~합계

# #2. 리스트 순서 변경
# [cols[0]]+cols[-2:]+cols[1:-2] #str + list+ list  => error

# #3. 변경된 리스트 적용
# df= df[cols]
# df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계     평균   결과
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.33  불합격
2       Kirbee   구로고   1  199  53  10  45       C  108  36.00  불합격
3    Appolonia   구로고   3  193  77  52  81       C  210  70.00   합격
4        Avery   구로고   2  187  59  35  43       C  137  45.67  불합격
5       Dallis  디지털고   1  209  97  57  76       C  230  76.67   합격
..         ...   ...  ..  ...  ..  ..  ..     ...  ...    ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.00   합격
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.00  불합격
98       Fiona   신림고   1  200  97  95  84       C  276  92.00   합격
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.33   합격
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.67   합격

[100 rows x 11 columns]

In [19]:
# df.value_counts('결과')  #같은 데이터가 몇 번 나오는지 개수를 세는 함수

결과
불합격    72
합격     28
Name: count, dtype: int64

In [ ]:
# df.index

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'], dtype='str', name='지원번호')

In [92]:
filt =df['수학']>80
filt.index

Index([], dtype='str', name='지원번호')

In [113]:
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

# index 삭제

In [ ]:
#row
#index삭제- 조건 사용해서 삭제
# 수학점수가 80점 미만 학생 삭제
filt = df['수학'] <80
# df2= df[filt]
# df2

#컬럼삭제
# df= df.drop(columns=['평균','결과'],inplace=True)

#index삭제
#1.row삭제
# df= df.drop(index=['1번','2번'],inplace=True)
#2.조건을 이용한 삭제
# df.drop(index=df[filt].index,inplace=True)

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#

# 인데스 추가
- loc[ ]이용, 컬럼 개수만큼 입력

In [ ]:
# df.loc['9번']=['홍길동','구로고', 190, 90, 80, 70, 60, 50, 'python']  #9번추가

# SW특기 부분 값 추가
# df.loc['4번','SW특기']= 'C'

# 부분 학교,사회,SW특기 컬럼에 값 수정
# df.loc['4번',['학교','SW특기']]= ['디지털고','python']
#df.loc['5번',['학교','사회','SW특기']]= ['디지털고',50,'python']
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬  디지털고  187   40   60   70  75  80      python
5번    김재욱  디지털고  188   15   20   10  35  50      python
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [119]:
df['체육']=100
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   체육
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  100
2번    강태원   구로고  184   40   35   50  55  25        Java  100
3번    강호림   구로고  168   80   75   70  80  75  Javascript  100
4번    김수찬   구로고  187   40   60   70  75  80         NaN  100
5번    김재욱   구로고  188   15   20   10  35  10         NaN  100
6번    박동현  디지털고  202   80  100   95  85  80           C  100
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  100
8번    승근열  디지털고  190  100   85   90  95  95          C#  100

In [125]:
#컬럼 이름 변경
#df.columns = [변경할 이름을 입력]
# df2= df[['이름','국어','영어']]
# df2.columns= [['name','kor','eng']] #컬럼명 변경
# df2

#부분 컬럼이름 변경 rename
# df.rename(columns={'이름':'name','국어':'kor','영어':'eng'},inplace=True)
# df

df.rename(columns={df.columns[1]:'school'}, inplace=True)

In [ ]:
#인덱스 삭제 퀴즈

df.columns
#국어,영어,수학,과학,사회 점수 합계 컬럼을 추가하고 합계점수가 350점 이상만 출력하시오.350점 미만 삭제 후 출력
df['합계']= df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
filt = df['합계'] >350
df[filt]    #350점이상만 출력
df.drop(index=df[~filt].index,inplace=True) # index삭제
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
6번    박동현  디지털고  202   80  100   95  85  80           C  440
8번    승근열  디지털고  190  100   85   90  95  95          C#  465