In [42]:
import pandas as pd

In [43]:
df=pd.read_excel('file/합계출산율_2026.xlsx',skiprows=28,nrows=2)
df.columns
df.set_index('Unnamed: 0',inplace=True)
df.index.name='제목'
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
제목,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [44]:
df.index.values[0]
df

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
제목,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [45]:
df.rename(index={'출생아\xa0수':'출생아 수'},inplace=True)
df

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
제목,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [46]:
df = df.T

In [47]:
df[(df['출생아 수'] >= 250) & (df['출생아 수'] <= 300)]

제목    출생아 수  합계 출산율
2020  272.3   0.837
2021  260.6   0.808
2025  254.3   0.800

In [50]:
df['출생아 수'].min()

np.float64(230.0)

In [49]:
round(df['출생아 수'].mean(),2)

np.float64(289.82)