In [2]:
import pandas as pd

In [41]:
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

# 문자열함수 .str 
-startswith,endswith,contains,lower,upper,capitalize
-split:분리,strip:공백제거,find:찾기,-1,len:글자수
-replace - 대체

In [ ]:
# #startswith: 강으로 시작하는 문자열
# df[df['이름'].str.startswith('강')]
# df.loc[df['이름'].str.startswith('강')]

# #contains 포함되어 있는 글자, ~ : not
# df[df['이름'].str.contains('열')]

# #lower-소문자/upper-대문자/capitalize-첫글자만 대문자
df['SW특기'].str.lower()
df['SW특기'].str.upper()
df['SW특기'].str.capitalize()

# #isin :여러개 검색['python','java']
langs=['python','java']
# df[df['SW특기'].str.lower().isin(langs)]  #소문자로 변경해서 리스트안에 값을 찾아줌.

# 
#df['SW특기'].str.lower().contains()
df['SW특기']
df['SW특기'].str.contains('Java',na=False)   
df[df['SW특기'].str.contains('Java',na=True)] #na=True :nan 데이터 출력
df[df['SW특기'].str.contains('Java',na=False)]  #na=False :nan 출력하지 않음
# df[df['SW특기'].str.lower().str.contains('java',na=False)] #소문자로 변경 후 검색

#unique
df['학교']
df['학교'].unique()

<StringArray>
['구로고', '디지털고']
Length: 2, dtype: str

In [12]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
#1개일때 str없이 사용, 여러개일때 str을 입력 후 사용
# df[0,2] =df.iloc[0,2].replace(',','')  #천단위 표시 제거 후 다시 저장
# df.iloc[0,2]
df['총 인구수'] = df['총 인구수'].str.replace(',','').astype(int)  #astype은 컬럼전체를 바꿀 때 사용가능
df['총 인구수']

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0     51159889
1      9323492
2      3251625
3      2357040
4      3041215
5      1398538
6      1440682
7      1093317
8       392154
9     13715016
10     1510181
11     1591815
12     2136299
13     1729337
14     1782183
15     2516753
16     3214016
17      666226
Name: 총 인구수, dtype: int64

In [ ]:
df=pd.read_csv('file/drinks.csv')
df['continent'].unique()

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str

In [27]:
df=pd.read_excel('file/students.xlsx',index_col='번호')
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [29]:
#특기에 c,java 포함된 학생추출
langs=['java','c']
df[df['SW특기'].str.lower().isin(langs)]['SW특기']
df.head(20)

#자바가 특기인 학생추출
df[df['SW특기'].str.lower().str.contains('java',na=False)]

             이름    학교  학년    키  국어  영어  수학        SW특기
번호
13       Ardene  디지털고   2  161  91  97  33        JAVA
14      Sibylle   구로고   1  197  82  81  38        JAVA
17        Alric   구로고   1  193  68  96  76        JAVA
18        Mozes   신림고   1  176  61  44  51        JAVA
20       Emelia   신림고   1  199  85  27  31  Javascript
30       Urbain  디지털고   3  197  83  72  36  Javascript
32       Hamnet   신림고   3  171  95  55  65  Javascript
36      Ainslee  디지털고   2  201  66  15  89  Javascript
41         Lyle  디지털고   3  164  55  47  73  Javascript
46          Nat  디지털고   2  171  70  38  82  Javascript
54          Ula   신림고   3  168  80  59  85        java
55     Emmanuel   구로고   2  191  63  27  83        JAVA
56        Valle   신림고   3  167  68  83  52        java
60      Malynda  디지털고   1  178  57  79  72        java
65         Kiri   신림고   3  178  64  83  68        JAVA
66       Joanie   신림고   1  200  75  24  85        java
68        Tresa   구로고   2  166  58  37  70        java
73        Moise  디지털고   3  185  90  83  65        JAVA
74        Lewes  디지털고   2  187  61  22  43        JAVA
76       Dionis  디지털고   1  192  58  40  63  Javascript
79       Vannie  디지털고   1  184  95  27  64  Javascript
82       Jamill   구로고   2  182  98   8  60        java
84          Ola  디지털고   3  170  84  77  77  Javascript
89       Norris  디지털고   3  174  68   9  51        java
91       Marika   신림고   2  189  89  22  32  Javascript
94         Kaja   신림고   1  202  53  44  78        java
95   Clementine   신림고   1  194  71  13  81        JAVA
100    Jonathan  디지털고   2  195  84  63  80        JAVA

In [20]:
df['학교']= df['학교'].str.replace('고교','고등학교')    #추가x, 변경o 
# df['학교']= df['학교']+'등학교'    무조건적인 추가

df['학교']

번호
1       신림고등학교
2       구로고등학교
3       구로고등학교
4       구로고등학교
5      디지털고등학교
        ...
96      신림고등학교
97      구로고등학교
98      신림고등학교
99      구로고등학교
100    디지털고등학교
Name: 학교, Length: 100, dtype: str

In [5]:
df.loc[df["이름"].str.startswith('E')]

           이름   학교  학년    키  국어  영어  수학        SW특기
번호
1     Eadmund  신림고   2  171  56  92  60           c
20     Emelia  신림고   1  199  85  27  31  Javascript
21  Evangelia  신림고   2  190  51  71  83      PYTHON
55   Emmanuel  구로고   2  191  63  27  83        JAVA
88      Emile  신림고   2  199  83  26  68      PYTHON

In [7]:
df[df['이름'].str.lower().str.contains('s')]

          이름    학교  학년    키  국어  영어  수학        SW특기
번호
5     Dallis  디지털고   1  209  97  57  76           C
14   Sibylle   구로고   1  197  82  81  38        JAVA
18     Mozes   신림고   1  176  61  44  51        JAVA
31    Holmes   구로고   1  184  51  21  87      Python
33  Robinson  디지털고   2  181  55  83  70      PYTHON
36   Ainslee  디지털고   2  201  66  15  89  Javascript
42  Sashenka  디지털고   2  195  69   7  55           c
44  Lisabeth   구로고   3  186  78  79  52           C
45      Mose   구로고   2  191  64  27  52
59   Kessiah  디지털고   2  162  66   0  67      PYTHON
62     Sheba  디지털고   1  184  88  90  67           c
63    Sarene   구로고   3  190  76  59  58      PYTHON
68     Tresa   구로고   2  166  58  37  70        java
73     Moise  디지털고   3  185  90  83  65        JAVA
74     Lewes  디지털고   2  187  61  22  43        JAVA
76    Dionis  디지털고   1  192  58  40  63  Javascript
80    Dallas   신림고   2  173  65  33  45      Python
89    Norris  디지털고   3  174  68   9  51        java